# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20161208_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclassification',
            name='exist',
            field=models.BooleanField(default=True),
        ),
    ]
