# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='item_name',
            field=models.CharField(default='item', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('budget', 'budget'), ('periodic', 'periodic')], default='budget', max_length=10),
        ),
    ]
